export const FETCH_ALL_BEGIN = "FETCH_ALL_BEGIN"
export const FETCH_ALL_ERROR = "FETCH_ALL_ERROR"
export const FETCH_ALL_SUCCESS = "FETCH_ALL_SUCCESS"

export const ADD_RES_BEGIN = "ADD_RES_BEGIN"
export const ADD_RES_ERROR = "ADD_RES_ERROR"
export const ADD_RES_SUCCESS = "ADD_RES_SUCCESS"

export const DISPLAY_ADD_FORM = "DISPLAY_ADD_FORM"
export const CLOSE_ADD_FORM = "CLOSE_ADD_FORM"

export const DISPLAY_EDIT_FORM = "DISPLAY_EDIT_FORM"
export const CLOSE_EDIT_FORM = "CLOSE_EDIT_FORM"

export const CLEAR_ALL_MODAL = "CLEAR_ALL_MODAL"
export const HANDLER_CHANGE = "HANDLER_CHANGE"

export const FORM_VALID_PASS = "FORM_VALID_PASS"
export const FORM_VALID_FAIL = "FORM_VALID_FAIL"

export const DISPLAY_ALERT = "DISPLAY_ALERT"
export const CLEAR_ALERT = "CLEAR_ALERT"
export const DISPLAY_POPUP_CONFIRM = "DISPLAY_POPUP_CONFIRM"

export const SET_EDIT_ID = "SET_EDIT_ID"
export const UPDATE_RES_BEGIN = "UPDATE_RES_BEGIN"
export const UPDATE_RES_SUCCESS = "UPDATE_RES_SUCCESS"


